service: tasks

custom:
  title: ML Task List
  swag:
    host: ambphvsfob.execute-api.us-east-1.amazonaws.com
    definitions:
      Task: ${file(./schema/task.json)}

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-${self:provider.stage}"

plugins:
  - swagger-export

package:
  exclude:
    - README.md
    - .*

functions:
  list:
    handler: list.handler
    events:
      - http:
          path: tasks
          method: get
          request:
            parameters:
              querystrings:
                user: true
          swag:
            summary: List tasks for a user
            responses:
              '200':
                description: A list of tasks for the specified user.
              '400':
                description: Bad Request. Most likely `user` parameter missing.
              '500':
                description: Internal Server Error.
  update:
    handler: update.handler
    events:
      - http:
          path: tasks/{id}
          method: patch
          request:
            parameters:
              paths:
                id: true
              body: Task
          swag:
            summary: Update a specific task for a user.
            responses:
              '200':
                description: Task updated successfully.
              '400':
                description: Bad Request.
              '500':
                description: Internal Server Error.
  add:
    handler: add.handler
    events:
      - http:
          path: tasks
          method: post
          request:
            parameters:
              body: Task
          swag:
            summary: Add a task for a specific user.
            responses:
              '200':
                description: Task added successfully.
              '400':
                description: Bad Request.
              '500':
                description: Internal Server Error.
  delete:
    handler: delete.handler
    events:
      - http:
          path: tasks/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          swag:
            summary: Delete a specific task for a user.
            responses:
              '200':
                description: Task deleted successfully.
              '400':
                description: Bad Request.
              '500':
                description: Internal Server Error.
  cron:
    handler: list.handler
    events:
      - schedule: cron(0 0 * * ? *)

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user
            AttributeType: S
        #   - AttributeName: description
        #     AttributeType: S
        #   - AttributeName: priority
        #     AttributeType: N
        #   - AttributeName: completed
        #     AttributeType: S
        KeySchema:
          - AttributeName: user
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: id
            KeySchema:
              - AttributeName: id
                KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
